version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/node:20.3.1
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            version="build-$CIRCLE_BUILD_NUM"
            echo $version
            docker build -t adeola1592/todo-app:$version .
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push adeola1592/todo-app:$version
      - run:
          name: Update Manifest File
          command: |
            TAG=$CIRCLE_BUILD_NUM
            ((TAG--))
            git clone https://github.com/Adeade151592/kube_manifest.git
            git config --global user.email "adeolaawoyemi.de@gmail.com"
            git config --global user.name "Adeade151592"
            cd kube_manifest
            echo $TAG
            sed -i "s/build-.*/build-$TAG/g" manifest/deployment.yaml
            cat manifest/deployment.yaml
            git add .
            git commit -m "new build with imgTag build-$TAG"
            git config credential.helper 'cache --timeout=120'
            git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/Adeade151592/kube_manifest.git main

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
